In [1]:
import pandas as pd

In [2]:
csv_url = 'https://www.dropbox.com/scl/fi/s8xeh94lwsz3wc4f21qo6/iris2.csv?rlkey=g6xb8yx626qmjoad1ghb5rgh9&st=005ksws0&dl=1'

iris_data = pd.read_csv(csv_url)

In [3]:
display(iris_data)

,sepal_length,sepal_width,petal_length,petal_width,species,species_id
0,5.1,3.5,1.4,0.2,setosa,1
1,4.9,3.0,1.4,0.2,setosa,1
2,4.7,3.2,1.3,0.2,setosa,1
3,4.6,3.1,1.5,0.2,setosa,1
4,5.0,3.6,1.4,0.2,setosa,1
...,...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,virginica,3
146,6.3,2.5,5.0,1.9,virginica,3
147,6.5,3.0,5.2,2.0,virginica,3
148,6.2,3.4,5.4,2.3,virginica,3
149,5.9,3.0,5.1,1.8,virginica,3

In [4]:
import sklearn
from sklearn.linear_model import LogisticRegression


iris_data = iris_data[iris_data['species_id'].between(1,2)]
print(iris_data.shape)

X = iris_data.drop(columns=['species','species_id'])
y = iris_data['species_id'] - 1

# Linear classifier
model = LogisticRegression()
model.fit(X, y)

coefs = list(model.coef_[0].round(4))
# Convert coefs to python float
coefs = [float(c) for c in coefs]


print(dict(zip(X.columns, coefs)))

(99, 6)
{'sepal_length': -0.0579, 'sepal_width': -0.8953, 'petal_length': 2.0453, 'petal_width': 0.8142}

In [31]:
coefs_dict = {'sepal_length': -0.0579, 'sepal_width': -0.8953, 'petal_length': 2.0453, 'petal_width': 0.8142}

# coefs_df = pd.DataFrame(coefs_dict.items(), columns=['feature', 'coef'])

# Create a dataframe from the dictionary, with the keys as columns and the values as rows
coefs_df = pd.DataFrame(coefs_dict.items(), columns=['feature', 'coef'])

coefs_series = coefs_df[['coef']].values
coefs_series = coefs_df.set_index('feature')['coef']

display(coefs_series)
X @ coefs_series
# coefs_series = coefs_series.reindex(X.columns)

feature
sepal_length   -0.0579
sepal_width    -0.8953
petal_length    2.0453
petal_width     0.8142
Name: coef, dtype: float64

0    -0.40258
1     0.05665
2    -0.31536
3     0.18902
4    -0.48632
       ...
95    6.55137
96    6.72232
97    6.89790
98    4.49798
99    6.60732
Length: 99, dtype: float64

In [28]:
X.columns , coefs_df[['coef']].index

(Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='str'),
 RangeIndex(start=0, stop=4, step=1))

In [ ]:


display(coefs_series)
# display(coefs_series.info())

multiplication_result = X @ coefs_series

display(multiplication_result)

prediction = (multiplication_result > 0).astype(int) + 1
prediction = prediction.values.flatten()


print(prediction.shape)
print(iris_data['species_id'].shape)

accuracy = (prediction == iris_data['species_id']).mean()
print(accuracy)

array([[-0.0579],
       [-0.8953],
       [ 2.0453],
       [ 0.8142]])

          0
0  -0.40258
1   0.05665
2  -0.31536
3   0.18902
4  -0.48632
..      ...
95  6.55137
96  6.72232
97  6.89790
98  4.49798
99  6.60732

[99 rows x 1 columns]

(99,)
(99,)
0.7878787878787878